"""
Run Groq-hosted judge LLM over inference_scaling candidates JSON (array of
{question, candidates: [...]}), same Groq wiring as scripts/generate_cot.py.

Usage:
  export GROQ_API_KEY=...  # or set in repo .env
  python core/verifier.py

  python core/verifier.py \\
    --input data/inference_scaling_candidates/scaling_candidates.json \\
    --output data/inference_scaling_candidates/scaling_verified.json
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = REPO_ROOT / "data/inference_scaling_candidates/scaling_candidates.json"
DEFAULT_OUTPUT = REPO_ROOT / "data/inference_scaling_candidates/scaling_verified.json"

VERIFIER_PROMPT = """You are a Logic Verifier. You will be given a question and {n} different "Thinking Paths" generated by a small model.
Your task:
1. Read EVERY path equally carefully. Do NOT favor path 0 (or first path) unless it is objectively the best after comparison.
2. Compare logic, completeness, and correctness of each path's reasoning and stated answer.
3. Choose the SINGLE best path among all {n}.
4. Output ONLY one integer — the chosen path's index — in the inclusive range [{min_i}, {max_i}]. No words, punctuation, or explanation.

Question: {question}
Candidates:
{candidates_text}

Chosen path index:"""


def build_user_content(question: str, candidates: list[str]) -> str:
    n = len(candidates)
    min_i, max_i = (0, n - 1) if n else (0, 0)
    lines = [f"--- Path {i} ---\n{c}" for i, c in enumerate(candidates)]
    candidates_text = "\n\n".join(lines)
    return VERIFIER_PROMPT.format(
        n=n,
        min_i=min_i,
        max_i=max_i,
        question=question,
        candidates_text=candidates_text,
    )


def shuffled_display_order(
    candidates: list[str], row_index: int, shuffle_seed: int
) -> tuple[list[str], list[int]]:
    """Return (reordered texts, orig_index_for_each_display_position)."""
    rng = random.Random((shuffle_seed * 1_000_003) ^ (row_index * 93_331))
    paired = list(enumerate(candidates))
    rng.shuffle(paired)
    orig_indices = [p[0] for p in paired]
    display = [p[1] for p in paired]
    return display, orig_indices


def parse_path_index(reply: str, n_paths: int) -> int | None:
    """Extract a valid path index from model output."""
    if not reply or not reply.strip() or n_paths <= 0:
        return None
    text = reply.strip()
    nums = [int(m.group()) for m in re.finditer(r"\b(\d+)\b", text)]
    for v in nums:
        if 0 <= v < n_paths:
            return v
    return None


def verify_best_path_groq(
    client: OpenAI, model: str, question: str, candidates: list[str]
) -> tuple[str | None, int | None]:
    """Call Groq judge; returns (raw_content, parsed_index_or_None)."""
    if not candidates:
        return None, None
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a meticulous logic verifier for math/word problems. "
                        "You must compare all candidate paths before choosing. "
                        "Respond with only one integer index (0 to N-1), nothing else."
                    ),
                },
                {"role": "user", "content": build_user_content(question, candidates)},
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content
        content = raw.strip() if raw else ""
        idx = parse_path_index(content, len(candidates))
        return content, idx
    except Exception as e:
        print(f"Groq error: {e}", file=sys.stderr)
        return None, None


def load_candidates(path: Path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError(f"Expected JSON array in {path}, got {type(data).__name__}")
    return data


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Groq verifier for scaling_candidates JSON.")
    p.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"path to scaling_candidates JSON (default: {DEFAULT_INPUT.relative_to(REPO_ROOT)})",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"where to write verification results JSON (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)})",
    )
    p.add_argument(
        "--groq-model",
        default=os.environ.get("GROQ_VERIFIER_MODEL") or "llama-3.3-70b-versatile",
        help='Groq model id (default: llama-3.3-70b-versatile; override with GROQ_VERIFIER_MODEL).',
    )
    p.add_argument(
        "--sleep",
        type=float,
        default=1.5,
        help="Seconds to pause after each API call (default: 1.5).",
    )
    p.add_argument(
        "--shuffle-seed",
        type=int,
        default=None,
        metavar="S",
        help=(
            "If set, randomize candidate order shown to the verifier (per question, reproducible). "
            "Reduces position bias where models default to path 0. Maps choice back to original index."
        ),
    )
    return p.parse_args()


def main() -> None:
    load_dotenv(REPO_ROOT / ".env")
    args = parse_args()

    input_path = args.input if args.input.is_absolute() else (REPO_ROOT / args.input)
    output_path = args.output if args.output.is_absolute() else (REPO_ROOT / args.output)

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print(
            "Set GROQ_API_KEY (e.g. export GROQ_API_KEY=... or add to .env).",
            file=sys.stderr,
        )
        sys.exit(1)

    client = OpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")
    model = args.groq_model

    if not input_path.is_file():
        print(f"Input not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    rows = load_candidates(input_path)
    final_decisions: list[dict] = []

    for i, entry in enumerate(rows):
        question = entry.get("question", "")
        candidates = entry.get("candidates") or []
        if not isinstance(candidates, list) or len(candidates) == 0:
            print(f"[{i + 1}/{len(rows)}] skip: missing or empty candidates", file=sys.stderr)
            final_decisions.append({
                "question": question,
                "error": "no_candidates",
                "raw_verifier_reply": None,
                "best_path_index": None,
                "best_reasoning": None,
            })
            continue

        print(f"[{i + 1}/{len(rows)}] Verifying: {question[:80]!r}{'…' if len(question) > 80 else ''}")

        orig_indices: list[int] | None = None
        to_verify = candidates
        if args.shuffle_seed is not None:
            to_verify, orig_indices = shuffled_display_order(
                candidates, i, args.shuffle_seed
            )

        raw, display_idx = verify_best_path_groq(client, model, question, to_verify)

        verifier_display_idx: int | None
        if display_idx is None:
            pick = candidates[0]
            best_orig_idx = 0
            verifier_display_idx = None
            print(
                f"  Could not parse index from reply {raw!r}; defaulting to original path {best_orig_idx}",
                file=sys.stderr,
            )
        else:
            verifier_display_idx = display_idx
            if orig_indices is not None:
                best_orig_idx = orig_indices[display_idx]
            else:
                best_orig_idx = display_idx
            pick = candidates[best_orig_idx]

        record: dict = {
            "question": question,
            "best_path_index": best_orig_idx,
            "raw_verifier_reply": raw,
            "verifier_display_index": verifier_display_idx,
            "best_reasoning": pick,
            "n_candidates": len(candidates),
        }
        if orig_indices is not None:
            record["candidate_order_shown_to_verifier"] = orig_indices
        final_decisions.append(record)

        time.sleep(args.sleep)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(final_decisions, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(final_decisions)} entries → {output_path}")


if __name__ == "__main__":
    main()
