"""
Run Groq-hosted judge LLM over inference_scaling candidates JSON (array of
{question, candidates: [...]}), same Groq wiring as scripts/generate_cot.py.

Usage:
  export GROQ_API_KEY=...  # or set in repo .env
  python core/verifier.py

  python core/verifier.py \\
    --input data/inference_scaling_candidates/scaling_candidates.json \\
    --output data/inference_scaling_candidates/scaling_verified.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = REPO_ROOT / "data/inference_scaling_candidates/scaling_candidates.json"
DEFAULT_OUTPUT = REPO_ROOT / "data/inference_scaling_candidates/scaling_verified.json"

VERIFIER_PROMPT = """You are a Logic Verifier. You will be given a question and {n} different "Thinking Paths" generated by a small model.
Your task:
1. Analyze the logic of each path.
2. Identify which path correctly identifies the answer and avoids logical fallacies.
3. Output ONLY the index (an integer from 0 to {max_i}) of the best path.

Question: {question}
Candidates:
{candidates_text}

Best Path Index:"""


def build_user_content(question: str, candidates: list[str]) -> str:
    n = len(candidates)
    max_i = n - 1 if n else 0
    lines = [f"--- Path {i} ---\n{c}" for i, c in enumerate(candidates)]
    candidates_text = "\n\n".join(lines)
    return VERIFIER_PROMPT.format(
        n=n,
        max_i=max_i,
        question=question,
        candidates_text=candidates_text,
    )


def parse_path_index(reply: str, n_paths: int) -> int | None:
    """Extract a valid path index from model output."""
    if not reply or not reply.strip() or n_paths <= 0:
        return None
    text = reply.strip()
    nums = [int(m.group()) for m in re.finditer(r"\b(\d+)\b", text)]
    for v in nums:
        if 0 <= v < n_paths:
            return v
    return None


def verify_best_path_groq(
    client: OpenAI, model: str, question: str, candidates: list[str]
) -> tuple[str | None, int | None]:
    """Call Groq judge; returns (raw_content, parsed_index_or_None)."""
    if not candidates:
        return None, None
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a meticulous logic verifier for math/word problems. "
                        "Respond with only one integer index, nothing else."
                    ),
                },
                {"role": "user", "content": build_user_content(question, candidates)},
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content
        content = raw.strip() if raw else ""
        idx = parse_path_index(content, len(candidates))
        return content, idx
    except Exception as e:
        print(f"Groq error: {e}", file=sys.stderr)
        return None, None


def load_candidates(path: Path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError(f"Expected JSON array in {path}, got {type(data).__name__}")
    return data


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Groq verifier for scaling_candidates JSON.")
    p.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"path to scaling_candidates JSON (default: {DEFAULT_INPUT.relative_to(REPO_ROOT)})",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"where to write verification results JSON (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)})",
    )
    p.add_argument(
        "--groq-model",
        default=os.environ.get("GROQ_VERIFIER_MODEL") or "llama-3.3-70b-versatile",
        help='Groq model id (default: llama-3.3-70b-versatile; override with GROQ_VERIFIER_MODEL).',
    )
    p.add_argument(
        "--sleep",
        type=float,
        default=1.5,
        help="Seconds to pause after each API call (default: 1.5).",
    )
    return p.parse_args()


def main() -> None:
    load_dotenv(REPO_ROOT / ".env")
    args = parse_args()

    input_path = args.input if args.input.is_absolute() else (REPO_ROOT / args.input)
    output_path = args.output if args.output.is_absolute() else (REPO_ROOT / args.output)

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print(
            "Set GROQ_API_KEY (e.g. export GROQ_API_KEY=... or add to .env).",
            file=sys.stderr,
        )
        sys.exit(1)

    client = OpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")
    model = args.groq_model

    if not input_path.is_file():
        print(f"Input not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    rows = load_candidates(input_path)
    final_decisions: list[dict] = []

    for i, entry in enumerate(rows):
        question = entry.get("question", "")
        candidates = entry.get("candidates") or []
        if not isinstance(candidates, list) or len(candidates) == 0:
            print(f"[{i + 1}/{len(rows)}] skip: missing or empty candidates", file=sys.stderr)
            final_decisions.append({
                "question": question,
                "error": "no_candidates",
                "raw_verifier_reply": None,
                "best_path_index": None,
                "best_reasoning": None,
            })
            continue

        print(f"[{i + 1}/{len(rows)}] Verifying: {question[:80]!r}{'…' if len(question) > 80 else ''}")
        raw, best_idx = verify_best_path_groq(client, model, question, candidates)

        if best_idx is None:
            pick = candidates[0]
            fallback = 0
            print(
                f"  Could not parse index from reply {raw!r}; defaulting to path {fallback}",
                file=sys.stderr,
            )
            best_idx = fallback
        else:
            pick = candidates[best_idx]

        final_decisions.append({
            "question": question,
            "best_path_index": best_idx,
            "raw_verifier_reply": raw,
            "best_reasoning": pick,
            "n_candidates": len(candidates),
        })

        time.sleep(args.sleep)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(final_decisions, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(final_decisions)} entries → {output_path}")


if __name__ == "__main__":
    main()
