import os
import json
from openai import OpenAI

# Use Groq or Gemini as the "Judge"
client = OpenAI(api_key="YOUR_API_KEY", base_url="https://api.groq.com/openai/v1")

VERIFIER_PROMPT = """
You are a Logic Verifier. You will be given a question and 5 different "Thinking Paths" generated by a small model.
Your task:
1. Analyze the logic of each path.
2. Identify which path correctly identifies the answer and avoids logical fallacies.
3. Output ONLY the index (0, 1, 2, 3, or 4) of the best path.

Question: {question}
Candidates:
{candidates_text}

Best Path Index:"""

def verify_best_path(question, candidates):
    candidates_text = ""
    for i, c in enumerate(candidates):
        candidates_text += f"--- Path {i} ---\n{c}\n"
    
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": VERIFIER_PROMPT.format(question=question, candidates_text=candidates_text)}],
        temperature=0
    )
    return response.choices[0].message.content.strip()

# Process the candidates
with open("scaling_candidates.json", "r") as f:
    data = json.load(f)

final_decisions = []
for entry in data:
    best_idx = verify_best_path(entry['question'], entry['candidates'])
    print(f"Question: {entry['question']} -> Best Path: {best_idx}")
    final_decisions.append({
        "question": entry['question'],
        "best_reasoning": entry['candidates'][int(best_idx[0])] # Take first char in case of extra text
    })